language: go

os:
  - linux

go:
  - 1.13.x
  - 1.14.x

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0

script:
  - go test -coverprofile=coverage.txt -covermode=atomic -bench . -benchmem -v ./...
  - golangci-lint run

after_success:
  - bash <(curl -s https://codecov.io/bash)
